application: egliselsh 
version: 5
runtime: python
api_version: 1

default_expiration: '3650d'

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  secure: optional
  login: admin

- url: /media
  static_dir: _generated_media
  secure: optional
  
- url: /static
  static_dir: static
  secure: optional

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /contribution/.*
  script: common/appenginepatch/main.py
  secure: always
  
- url: /.*
  script: common/appenginepatch/main.py
  secure: optional